package pack1;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.io.*;
import javax.swing.*;
import org.jfree.chart.*;
/**
 *
 * @author Girish Menon
 */import java.util.*;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.ws.WebServiceRef;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.util.Properties;
 
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
 
public class Cilent extends javax.swing.JFrame {

    /**
     * Creates new form Cilent
     */
    String result1,se;
    int valid=0,amount1=0,amount2=0;
        ;
    long starttime,starttime1,elapsedtime,starttime2,elapsedtime2,elapsedtime1;
   
    Date date = new Date();
    SimpleDateFormat format1=new SimpleDateFormat("dd-MM-yyyy");
            String today=format1.format(date.getTime());
            File image=null ;
    public Cilent() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     */
    @WebServiceRef(wsdlLocation ="169.254.209.54:8080/Serverwebservice/rules?WSDL")
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page1 = new javax.swing.JFrame();
        newaccount = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        checkaccount = new javax.swing.JButton();
        checkaccount1 = new javax.swing.JButton();
        withdrawlbtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Datelabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        performance = new javax.swing.JButton();
        newaccountf = new javax.swing.JFrame();
        newusubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        accname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        page2 = new javax.swing.JFrame();
        checktext1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        checktext2 = new javax.swing.JLabel();
        jaddress1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        depositpage = new javax.swing.JFrame();
        depositno = new javax.swing.JTextField();
        depositamount = new javax.swing.JTextField();
        depositbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        withdrawlpage = new javax.swing.JFrame();
        withno = new javax.swing.JTextField();
        withamount = new javax.swing.JTextField();
        withbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        db = new javax.swing.JFileChooser();
        fundtransfer = new javax.swing.JFrame();
        transfer = new javax.swing.JButton();
        tacc1 = new javax.swing.JTextField();
        tacc2 = new javax.swing.JTextField();
        tamount = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        performancechart = new javax.swing.JFrame();
        lhost = new javax.swing.JButton();
        vbox = new javax.swing.JButton();
        pback = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cclient = new javax.swing.JButton();
        userl = new javax.swing.JTextField();
        passl = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginl = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        page1.setMinimumSize(new java.awt.Dimension(500, 400));

        newaccount.setText("New Account");
        newaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newaccountActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("VETO ENFORCE");

        checkaccount.setText("Check Balance");
        checkaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkaccountActionPerformed(evt);
            }
        });

        checkaccount1.setText("Deposit");
        checkaccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkaccount1ActionPerformed(evt);
            }
        });

        withdrawlbtn.setText("Withdrawl");
        withdrawlbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawlbtnActionPerformed(evt);
            }
        });

        jButton7.setText("Close");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel10.setText("Date :");

        jButton8.setText("Fund Transfer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        performance.setText("Performance");
        performance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page1Layout = new javax.swing.GroupLayout(page1.getContentPane());
        page1.getContentPane().setLayout(page1Layout);
        page1Layout.setHorizontalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addComponent(Datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
            .addGroup(page1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(page1Layout.createSequentialGroup()
                        .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkaccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newaccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkaccount1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(withdrawlbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(performance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        page1Layout.setVerticalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(56, 56, 56)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newaccount)
                    .addComponent(checkaccount1))
                .addGap(52, 52, 52)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkaccount)
                    .addComponent(withdrawlbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(performance))
                .addGap(40, 40, 40)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Datelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        newaccountf.setMinimumSize(new java.awt.Dimension(500, 665));

        newusubmit.setText("Submit");
        newusubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newusubmitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("NEW ACCOUNT");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NAME");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ADDRESS");

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel11.setText("UPLOAD PICTURE");

        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("SEX");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("DOB");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Mobile");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Email ID");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Passportl ID");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Nomminee");

        javax.swing.GroupLayout newaccountfLayout = new javax.swing.GroupLayout(newaccountf.getContentPane());
        newaccountf.getContentPane().setLayout(newaccountfLayout);
        newaccountfLayout.setHorizontalGroup(
            newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newaccountfLayout.createSequentialGroup()
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newaccountfLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel4))
                    .addGroup(newaccountfLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newaccountfLayout.createSequentialGroup()
                                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(newaccountfLayout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(gender)
                                            .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(accname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                                    .addGroup(newaccountfLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(newaccountfLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(browse, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(newusubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addComponent(jButton6)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        newaccountfLayout.setVerticalGroup(
            newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newaccountfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newaccountfLayout.createSequentialGroup()
                        .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(accname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browse)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newaccountfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newusubmit)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        page2.setMinimumSize(new java.awt.Dimension(500, 390));

        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("ENTER ACCOUNT NUMBER");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("BALANCE");

        jButton5.setText("CANCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        checktext2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Magneto", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 102, 51));
        jLabel21.setText("BALANCE");

        javax.swing.GroupLayout page2Layout = new javax.swing.GroupLayout(page2.getContentPane());
        page2.getContentPane().setLayout(page2Layout);
        page2Layout.setHorizontalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checktext1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(page2Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5))
                                .addComponent(checktext2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        page2Layout.setVerticalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel21)
                .addGap(70, 70, 70)
                .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(checktext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checktext2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(56, 56, 56))
        );

        depositpage.setMinimumSize(new java.awt.Dimension(500, 300));

        depositbtn.setText("DEPOSIT");
        depositbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositbtnActionPerformed(evt);
            }
        });

        jLabel12.setText("ENTER ACCOUNT NUMBER");

        jLabel13.setText("AMOUNT");

        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositpageLayout = new javax.swing.GroupLayout(depositpage.getContentPane());
        depositpage.getContentPane().setLayout(depositpageLayout);
        depositpageLayout.setHorizontalGroup(
            depositpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositpageLayout.createSequentialGroup()
                .addGroup(depositpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, depositpageLayout.createSequentialGroup()
                        .addGroup(depositpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(depositpageLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(depositpageLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(depositpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depositamount, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(depositno)))
                    .addGroup(depositpageLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(depositbtn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(96, 96, 96))
        );
        depositpageLayout.setVerticalGroup(
            depositpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositpageLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(depositpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(59, 59, 59)
                .addGroup(depositpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(45, 45, 45)
                .addGroup(depositpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositbtn)
                    .addComponent(jButton3))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        withdrawlpage.setMinimumSize(new java.awt.Dimension(500, 300));

        withbtn.setText("Withdraw");
        withbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withbtnActionPerformed(evt);
            }
        });

        jLabel14.setText("ENTER ACCOUNT NUMBER");

        jLabel15.setText("AMOUNT");

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdrawlpageLayout = new javax.swing.GroupLayout(withdrawlpage.getContentPane());
        withdrawlpage.getContentPane().setLayout(withdrawlpageLayout);
        withdrawlpageLayout.setHorizontalGroup(
            withdrawlpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawlpageLayout.createSequentialGroup()
                .addGroup(withdrawlpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, withdrawlpageLayout.createSequentialGroup()
                        .addGroup(withdrawlpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(withdrawlpageLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(withdrawlpageLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(withdrawlpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(withamount, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(withno)))
                    .addGroup(withdrawlpageLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(withbtn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addGap(96, 96, 96))
        );
        withdrawlpageLayout.setVerticalGroup(
            withdrawlpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawlpageLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(withdrawlpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(59, 59, 59)
                .addGroup(withdrawlpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(45, 45, 45)
                .addGroup(withdrawlpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withbtn)
                    .addComponent(jButton4))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        fundtransfer.setMinimumSize(new java.awt.Dimension(450, 300));

        transfer.setText("Transfer");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Magneto", 1, 24)); // NOI18N
        jLabel16.setText("FUND TRANSFER");

        jLabel17.setText("ACC NO OF SENDER");

        jLabel18.setText("ACC NO OF RECIPIENT ");

        jLabel19.setText("AMOUNT");

        javax.swing.GroupLayout fundtransferLayout = new javax.swing.GroupLayout(fundtransfer.getContentPane());
        fundtransfer.getContentPane().setLayout(fundtransferLayout);
        fundtransferLayout.setHorizontalGroup(
            fundtransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundtransferLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundtransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fundtransferLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundtransferLayout.createSequentialGroup()
                        .addGroup(fundtransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(104, 104, 104)
                        .addGroup(fundtransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tacc1)
                            .addComponent(tacc2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fundtransferLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(transfer)
                                .addGap(18, 18, 18)
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tamount))))
                .addGap(87, 87, 87))
        );
        fundtransferLayout.setVerticalGroup(
            fundtransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundtransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(fundtransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tacc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(38, 38, 38)
                .addGroup(fundtransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tacc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(36, 36, 36)
                .addGroup(fundtransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(51, 51, 51)
                .addGroup(fundtransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(transfer))
                .addGap(24, 24, 24))
        );

        performancechart.setMinimumSize(new java.awt.Dimension(457, 210));

        lhost.setText("Local Host");
        lhost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lhostActionPerformed(evt);
            }
        });

        vbox.setText("Virtual box");
        vbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vboxActionPerformed(evt);
            }
        });

        pback.setText("Back");
        pback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbackActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel20.setText("PERFORMANCE OF WEBSERVICE");

        cclient.setText("Client");
        cclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cclientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout performancechartLayout = new javax.swing.GroupLayout(performancechart.getContentPane());
        performancechart.getContentPane().setLayout(performancechartLayout);
        performancechartLayout.setHorizontalGroup(
            performancechartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(performancechartLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel20)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(performancechartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lhost)
                .addGap(40, 40, 40)
                .addComponent(vbox)
                .addGap(39, 39, 39)
                .addComponent(cclient, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, performancechartLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pback))
        );
        performancechartLayout.setVerticalGroup(
            performancechartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(performancechartLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel20)
                .addGap(66, 66, 66)
                .addGroup(performancechartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vbox)
                    .addComponent(cclient)
                    .addComponent(lhost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(pback))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANK CLIENT");
        setBackground(new java.awt.Color(255, 0, 51));
        setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("USERNAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD");

        loginl.setText("LOGIN");
        loginl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginlActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("AUTHENTICATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginl)
                        .addGap(20, 20, 20)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(userl)
                    .addComponent(passl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(loginl))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newaccountActionPerformed
newaccountf.show();    
 page1.hide();// TODO add your handling code here:
    }//GEN-LAST:event_newaccountActionPerformed

    public void mail(String g,String m)
    {
   final String username = "cstuskerz@gmail.com";
		final String password = "2010cs2014";
 
		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");
 
		Session session = Session.getInstance(props,
		  new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		  });
 
		try {
 
			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("VETOENFORCETEAM@gmail.com"));
			message.setRecipients(Message.RecipientType.TO,
				InternetAddress.parse(g));
			message.setSubject("VETO ENFORCE");
			message.setText(m);
 
			Transport.send(message);
 
			System.out.println("Done");
 
		} catch (MessagingException e) {
			throw new RuntimeException(e);
		}
    
    
    }
    private void newusubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newusubmitActionPerformed
      
        String n = accname.getText();
     String p = address.getText();
     String g=gender.getText();
     String mobi=mobile.getText();
    
     String ppid=pid.getText();
     int pid1=Integer.parseInt(ppid);
     String ei=email.getText();
     String nomm=nom.getText();
     String dobb=dob.getText();
     int b=0;
     String msg="Dear "+ n +"," + "\n\n Thank you for being a part of VETO ENFORCE TEAM. Your account has been created successfully."+ "\n\nRegards,"+ "\n\n VETO ENFORCE TEAM";
        
    
     
        try {
       
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://169.254.209.54:3306/cilent","root","admin");
        Statement stmt=con.createStatement();
        Statement stmt1=con.createStatement();
        
        String count="select count(*) from newaccount";
        Statement stmt2=con.createStatement();
        ResultSet rs=stmt2.executeQuery(count);
        Statement stmt3=con.createStatement();
        rs.next();
        int countint=rs.getInt("count(*)");
        int count1=10000+countint;
        int card=(1000+count1);
        String pin="1000";
      
        
        
        
        
        String sql2="INSERT INTO atm (cardnumber,pinnumber) VALUES ('"+(count1)+"', AES_ENCRYPT('"+(count1)+"', '"+(pin)+"'))";
        String sql="Insert into newaccount(accno,accname,address,joindate,gen,mob,passid,eid,nomi,dobi) values('"+(count1)+"','"+(n)+"','"+(p)+"','"+(today)+"','"+(g)+"','"+(mobi)+"','"+(pid1)+"','"+(ei)+"','"+(nomm)+"','"+(dobb)+"')";
        String sql1="insert into account(accno,amount,pic) values(?,?,?)";
        PreparedStatement psmnt=con.prepareStatement(sql1);
        stmt.executeUpdate(sql);
        psmnt.setInt(1,count1);
        psmnt.setInt(2,b);
        FileInputStream fis = new FileInputStream(image);
        psmnt.setBinaryStream(3, (InputStream)fis, (int)(image.length()));
        psmnt.executeUpdate();
        
        stmt3.executeUpdate(sql2);
        
        JOptionPane.showMessageDialog(null, "NEW ACCOUNT CREATED");
        page1.show();
        mail(ei,msg);
       newaccountf.hide();  
       
        
        accname.setText("");
        address.setText("");
        stmt.close();
       stmt1.close();
        psmnt.close();
        rs.close();
        stmt2.close();
        con.close();
      }
   catch(Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_newusubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void loginlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginlActionPerformed
        String user=userl.getText();
        String pwd=new String(passl.getPassword());
        
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://169.254.209.54:3306/login","root","admin");
        Statement stmt=con.createStatement();
        String sql="SELECT * FROM logindb where password=AES_ENCRYPT('"+(user)+"', '"+(pwd)+"')";
        ResultSet rs=stmt.executeQuery(sql);
        String sql1="SELECT count(*) FROM logindb where name='"+(user)+"' ";
        Statement stmt1=con.createStatement();
        ResultSet rs1=stmt1.executeQuery(sql1);
       
        
        
        
        int tmp=0;
        while(rs.next())
        {
        String uname=rs.getString("name");
              
                   
           while(rs1.next())
           {
           int count=rs1.getInt("count(*)");
           
           if((user.equals(uname))&&(count==1))
           {
           page1.show();
          
            
           Datelabel.setText(today);
           this.hide();
           
           
           tmp++;
           
           }
        }
        }
        if (tmp==0) {
             userl.setText("");
        passl.setText("");
        JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
       }
        
        rs.close();
        rs1.close();
        stmt.close();
       stmt1.close();
        
        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(this,e.getMessage());
       
        }
        
    }//GEN-LAST:event_loginlActionPerformed

    private void checkaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkaccountActionPerformed
   page2.show();
    }//GEN-LAST:event_checkaccountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try
    {
       
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://169.254.209.54:3306/cilent","root","admin");
        String nw=checktext1.getText();
        int n=Integer.parseInt(nw);
        
        Statement stmt=con.createStatement();
        String sql="select * from account";
        ResultSet rs=stmt.executeQuery(sql);
        
             
        int tmp=0;
            
        
        while(rs.next())
        {
     
        String p=rs.getString("amount");
        int no=rs.getInt("Accno");
        
        if(n==no)
        {
        checktext1.setText(nw);
        checktext2.setText(p);
       
        tmp++;
                }
        
        }
      
      
      
       
          if(tmp==0)
        {
        JOptionPane.showMessageDialog(null,"ACCOUNT NOT FOUND");
        checktext1.setText("");
        }
          
       
        
            rs.close();
            stmt.close();
    
    }
 
    catch(Exception e){
    JOptionPane.showMessageDialog(this,e.getMessage());
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkaccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkaccount1ActionPerformed
depositpage.show();        // TODO add your handling code here:
    }//GEN-LAST:event_checkaccount1ActionPerformed

    private void depositbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositbtnActionPerformed
       
        try{
            
          String daccnon=depositno.getText();
          int daccno=Integer.parseInt(daccnon);
          
          String damount=depositamount.getText();  
           int dam=Integer.parseInt(damount);
           int valid=0;
         
        
          Class.forName("com.mysql.jdbc.Driver");
          Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://169.254.209.54:3306/cilent","root","admin");
          Statement stmt=con.createStatement();
          Statement stmt1=con.createStatement();
          ResultSet rs1=stmt1.executeQuery("Select accname,eid from newaccount where accno='"+(daccno)+"'");
          rs1.next();
          String e=rs1.getString("eid");
          String na=rs1.getString("accname");
          stmt1.close();
          rs1.close();
         
           String msg="Dear "+ na +"," + "\n\n"+ damount +" RS deposited to your account. Thank you for your transaction."+ "\n\nRegards,"+ "\n\n VETO ENFORCE TEAM";
          
          String sql="select * from account";
          
          ResultSet rs=stmt.executeQuery(sql);
          int tmp=0;
          while(rs.next())
          {
          int daccno1=rs.getInt("accno");
          int damount1=rs.getInt("amount");
          if(daccno==daccno1)
                  {
                             
                  tmp++;
                  starttime1=System.nanoTime();
                   depositrule(dam);
                   elapsedtime1=System.nanoTime()-starttime1;
                   starttime1=starttime1/1000000;
          elapsedtime1=elapsedtime1/1000000;
          Statement st=con.createStatement();
          st.executeUpdate("update vboxchart set ctime1='"+(elapsedtime1)+"'");
          st.close();
          
          if(result1.equals("false"))
          {
          depositno.setText("");
          depositamount.setText("");
          valid=1;
              JOptionPane.showMessageDialog(null,"Amount too high");
          }
          if(valid==0)
          {
               String sql1 = "Update account set amount='" + (damount1+dam)+ "' where accno="+(daccno)+"";
               stmt.executeUpdate(sql1);
               JOptionPane.showMessageDialog(null, "DEPOSITED");
               mail(e,msg);
               depositno.setText("");
         depositamount.setText("");       
                  }
                   
          }
          }
        
      
         if(tmp==0)
        {
        JOptionPane.showMessageDialog(null,"ACCOUNT NOT FOUND");
        depositno.setText("");
         depositamount.setText("");
        }
          
          rs.close();
        
        stmt.close();
          
      }catch(Exception e){
      JOptionPane.showMessageDialog(this,e.getMessage());
      }

    }//GEN-LAST:event_depositbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        depositpage.dispose();
       depositno.setText("");
         depositamount.setText("");
        page1.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void withdrawlbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawlbtnActionPerformed
withdrawlpage.show();        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawlbtnActionPerformed

    private void withbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withbtnActionPerformed
       
        try{
          String waccno=withno.getText();
          String wamount=withamount.getText();
          int wam=Integer.parseInt(wamount);
          
          int tmp=0,valid=0;
           Class.forName("com.mysql.jdbc.Driver");
          Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://169.254.209.54:3306/cilent","root","admin");
          
          starttime=System.nanoTime();
          webrule(wam);
          elapsedtime=System.nanoTime()-starttime;
          starttime=starttime/1000000;
          elapsedtime=elapsedtime/1000000;
           Statement st=con.createStatement();
          st.executeUpdate("Update vboxchart set ctime=('"+(elapsedtime)+"')");
          st.close();
         Statement stmt=con.createStatement();
          
          Statement stmt1=con.createStatement();
          ResultSet rs1=stmt1.executeQuery("Select accname,eid from newaccount where accno='"+(waccno)+"'");
          rs1.next();
          String e=rs1.getString("eid");
          String na=rs1.getString("accname");
          stmt1.close();
          rs1.close();
         
           String msg="Dear "+ na +"," + "\n\n"+ wamount +" RS debited from your account. Thank you for your transaction."+ "\n\nRegards,"+ "\n\n VETO ENFORCE TEAM";
          
          String sql="select * from account";
          ResultSet rs=stmt.executeQuery(sql);
          
          while(rs.next())
          {
          String waccno1=rs.getString("accno");
          int wamount1=rs.getInt("amount");
          
          
          
          if(waccno.equals(waccno1))
                  {
                      tmp++;
                      if((wamount1<=0||(wamount1-wam)<=0))
          {
           JOptionPane.showMessageDialog(null, "No balance");
           withno.setText("");
         withamount.setText("");
         valid=1;
          }
                        
           if(result1.equals("false"))
          {
          JOptionPane.showMessageDialog(null,"AMOUNT IS TOO HIGH");
          valid=1;
          }
                        if(valid==0)
                        {
                                
               String sql1 = "Update account set amount='" + (wamount1-wam)+ "' where accno="+(waccno)+"";
               stmt.executeUpdate(sql1);
               JOptionPane.showMessageDialog(null, "WITHDRAWL SUCESSFULL");
                  withno.setText("");
         withamount.setText("");    
         mail(e,msg);
                  }
                  }
           
          }
         
          
           if(tmp==0)
        {
        JOptionPane.showMessageDialog(null,"ACCOUNT NOT FOUND");
        withno.setText("");
         withamount.setText("");
        }
        rs.close();
        stmt.close();  
      }catch(Exception e){
      JOptionPane.showMessageDialog(this,e.getMessage());
      }
                                     
    }//GEN-LAST:event_withbtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
page1.show();
withno.setText("");
withamount.setText("");
withdrawlpage.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
page1.show();
page2.hide();
 checktext1.setText("");
         checktext2.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
page1.show();
newaccountf.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

   
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed

      int v=db.showOpenDialog(this);

      if(v==JFileChooser.APPROVE_OPTION)
      {
      File file=db.getSelectedFile();
      String name=file.toString();
      image=new File(name);
      
      }                

    }//GEN-LAST:event_browseActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        page1.hide();
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://169.254.209.54:3306/cilent","root","admin");
        Statement stmt=con.createStatement();
        Statement stmt1=con.createStatement();
        String sql="Select accno,amount from account";
        ResultSet rs=stmt.executeQuery(sql);
        int tmp=0,flag1;
        
        String ta1=tacc1.getText();
        int ta11=Integer.parseInt(ta1);
        String ta2=tacc2.getText();
        int ta21=Integer.parseInt(ta2);
        String ta=tamount.getText();
        int ta0=Integer.parseInt(ta);
        int flag=0;
        while(rs.next())
        {
        int acc1=rs.getInt("accno");
       
                   
        if(ta11==acc1)
            {
                flag=flag+1;
                amount1=rs.getInt("amount");
            }
        
        if(ta21==acc1)
            {
                flag=flag+1;
                amount2=rs.getInt("amount");
            }
       
       
       if(flag==2)
            {
                tmp++; 
                starttime2=System.nanoTime();
                fundrule(ta0);
                elapsedtime2=System.nanoTime()-starttime2;    
                elapsedtime2=elapsedtime2/1000000;
                Statement st=con.createStatement();
          st.executeUpdate("update vboxchart set ctime2='"+(elapsedtime2)+"'");
          st.close();
                if(result1.equals("false"))
                     {
                          valid=1;
                     }
                
                 else{
                        String sql1= "Update account set amount='" +(amount2+ta0)+ "' where accno="+(ta21)+"";
                        String sql2= "Update account set amount='" +(amount1-ta0)+ "' where accno="+(ta11)+"";
                        stmt.executeUpdate(sql1);
                        stmt.executeUpdate(sql2);
                        JOptionPane.showMessageDialog(null, "AMOUNT TRANSFERED SUCCESSFULLY ");
               
                     }
            }
        }
        if(tmp==0)
        {
            JOptionPane.showMessageDialog(null, "WRONG A/C NUMBER!!!");
        }
        
        
        if(valid==1)
        {
        JOptionPane.showMessageDialog(null, "Amount should be greater than 1000");
        tacc1.setText("");
        tacc2.setText("");
        tamount.setText("");
        page1.show();
        fundtransfer.hide();
        }
            rs.close();
            stmt.close();
        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(this,e.getMessage());
      
        }
        tacc1.setText("");
        tacc2.setText("");
        tamount.setText("");
        page1.show();
        fundtransfer.hide();
            
        
    }//GEN-LAST:event_transferActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
page1.show();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
fundtransfer.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void performanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceActionPerformed
      performancechart.show();
      page1.hide();
    }//GEN-LAST:event_performanceActionPerformed

    private void lhostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lhostActionPerformed
       double n1=0;
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
    dataset.setValue(elapsedtime,"TIME ELAPSED IN MILLISEC","Withdraw");
    dataset.setValue(elapsedtime1,"TIME ELAPSED IN MILLISEC","Deposit");
    dataset.addValue(elapsedtime2,"TIME ELAPSED IN MILLISEC","Transfer");
    
    
    JFreeChart chart=ChartFactory.createBarChart3D("PERFORMANCE OF WEBSERVICE","WEBSERVICE","TIME IN MILLISEC", dataset, PlotOrientation.VERTICAL,false, true,false);
    chart.setBackgroundPaint(Color.red);
    
    CategoryPlot p=chart.getCategoryPlot();
    p.setRangeGridlinePaint(Color.black);
    ChartFrame frame1=new ChartFrame("PERFORMANCE CHART",chart);
    
    frame1.setSize(400,350); 
    
    frame1.show();
    
    
    

    }//GEN-LAST:event_lhostActionPerformed

    private void vboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vboxActionPerformed
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://169.254.209.54:3306/cilent","root","admin");
        String sql="Select * from vboxchart";
        Statement stmt4=con.createStatement();
        ResultSet rs4=stmt4.executeQuery(sql);
        rs4.next();
        int elapsedtime=rs4.getInt("etime");
        stmt4.close();
        rs4.close();
                
        
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        dataset.setValue(elapsedtime,"Time in ms","Withdraw");
        JFreeChart chart=ChartFactory.createBarChart3D("Performance","web","time in mm", dataset, PlotOrientation.VERTICAL, false, true,false);
        chart.setBackgroundPaint(Color.red);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame=new ChartFrame("VBOX",chart);
        frame.show();
        frame.setSize(300,300);
        }catch(Exception e)
        
        {
        JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_vboxActionPerformed

    private void pbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbackActionPerformed
performancechart.hide();
page1.show();// TODO add your handling code here:
    }//GEN-LAST:event_pbackActionPerformed

    private void cclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cclientActionPerformed
         try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://169.254.209.54:3306/cilent","root","admin");
        String sql="Select * from vboxchart";
        Statement stmt4=con.createStatement();
        ResultSet rs4=stmt4.executeQuery(sql);
        rs4.next();
        int elapsedtime=rs4.getInt("ctime");
        stmt4.close();
        rs4.close();
                
        
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        dataset.setValue(elapsedtime,"Time in ms","Withdraw");
        JFreeChart chart=ChartFactory.createBarChart3D("Performance","web","time in mm", dataset, PlotOrientation.VERTICAL, false, true,false);
        chart.setBackgroundPaint(Color.red);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame=new ChartFrame("Client",chart);
        frame.show();
        frame.setSize(300,300);
        }catch(Exception e)
        
        {
        JOptionPane.showMessageDialog(this,e.getMessage());
        }
                    // TODO add your handling code here:
    }//GEN-LAST:event_cclientActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cilent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cilent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cilent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cilent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cilent().setVisible(true);
                
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Datelabel;
    private javax.swing.JTextField accname;
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JButton browse;
    private javax.swing.JButton cclient;
    private javax.swing.JButton checkaccount;
    private javax.swing.JButton checkaccount1;
    private javax.swing.JTextField checktext1;
    private javax.swing.JLabel checktext2;
    private javax.swing.JFileChooser db;
    private javax.swing.JTextField depositamount;
    private javax.swing.JButton depositbtn;
    private javax.swing.JTextField depositno;
    private javax.swing.JFrame depositpage;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JFrame fundtransfer;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jaddress1;
    private javax.swing.JButton lhost;
    private javax.swing.JButton loginl;
    private javax.swing.JTextField mobile;
    private javax.swing.JButton newaccount;
    private javax.swing.JFrame newaccountf;
    private javax.swing.JButton newusubmit;
    private javax.swing.JTextField nom;
    private javax.swing.JFrame page1;
    private javax.swing.JFrame page2;
    private javax.swing.JPasswordField passl;
    private javax.swing.JButton pback;
    private javax.swing.JButton performance;
    private javax.swing.JFrame performancechart;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField tacc1;
    private javax.swing.JTextField tacc2;
    private javax.swing.JTextField tamount;
    private javax.swing.JButton transfer;
    private javax.swing.JTextField userl;
    private javax.swing.JButton vbox;
    private javax.swing.JTextField withamount;
    private javax.swing.JButton withbtn;
    private javax.swing.JButton withdrawlbtn;
    private javax.swing.JFrame withdrawlpage;
    private javax.swing.JTextField withno;
    // End of variables declaration//GEN-END:variables

    private  String webrule(int x) {
        pack1.Rules_Service service = new pack1.Rules_Service();
        pack1.Rules port = service.getRulesPort();
        java.lang.String result=port.webrule(x);
        result1=result;
        return null;
    }

    private String depositrule(int y) {
        pack1.Rules_Service service = new pack1.Rules_Service();
        pack1.Rules port = service.getRulesPort();
        java.lang.String result=port.depositrule(y);
         
         result1=result;
         
        return null;
    }

    private  String fundrule(int famount) {
        pack1.Rules_Service service = new pack1.Rules_Service();
        pack1.Rules port = service.getRulesPort();
        java.lang.String result=port.fundrule(famount);
        result1=result;
        return null;
    }

  
}
